name: Deploy

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build_and_push_image:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Build the Docker image
        run: docker build . --file Dockerfile -t auliahanifan/hello-world:${GITHUB_SHA::6}
      - name: docker tag
        run: docker tag auliahanifan/hello-world:${GITHUB_SHA::6} cloud.canister.io:5000/auliahanifan/hello-world:${GITHUB_SHA::6}
      - name: docker login
        env:
          DOCKER_USERNAME: ${{secrets.CANISTER_USERNAME}}
          DOCKER_PASSWORD: ${{secrets.CANISTER_PASSWORD}}
        run: |
          docker login --username=$DOCKER_USERNAME --password=$DOCKER_PASSWORD cloud.canister.io:5000

      - name: Docker Push
        run: docker push cloud.canister.io:5000/auliahanifan/hello-world:${GITHUB_SHA::6}
