name: Deploy

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build_and_push_image:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Build the Docker image
        run: docker build . --file Dockerfile -t auliahanifan/hello-world:${GITHUB_SHA::6}
      - name: docker tag
        run: docker tag auliahanifan/hello-world:${GITHUB_SHA::6} cloud.canister.io:5000/auliahanifan/hello-world:${GITHUB_SHA::6}
      - name: docker login
        env:
          DOCKER_USERNAME: ${{secrets.CANISTER_USERNAME}}
          DOCKER_PASSWORD: ${{secrets.CANISTER_PASSWORD}}
        run: |
          docker login --username=$DOCKER_USERNAME --password=$DOCKER_PASSWORD cloud.canister.io:5000

      - name: Docker Push
        run: docker push cloud.canister.io:5000/auliahanifan/hello-world:${GITHUB_SHA::6}
  deploy_to_prod:
    needs: build_and_push_image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v0.1.7
        env:
          DOCKER_USERNAME: ${{secrets.CANISTER_USERNAME}}
          DOCKER_PASSWORD: ${{secrets.CANISTER_PASSWORD}}
          DEPLOY_CONFIG_FOLDER: ${{secrets.DEPLOY_CONFIG_FOLDER}}
          HELLO_TAG: ${{GITHUB_SHA::6}}
        with:
          host: ${{ secrets.SSH_SERVER }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          envs: DOCKER_USERNAME,DOCKER_PASSWORD,DEPLOY_CONFIG_FOLDER,HELLO_TAG
          script: |
              cd $DEPLOY_CONFIG_FOLDER
              git pull origin main
              docker login --username=$DOCKER_USERNAME --password=$DOCKER_PASSWORD cloud.canister.io:5000
              HELLO_TAG=$HELLO_TAG docker stack deploy -c hello-world.docker-compose.yml hello --with-registry-auth
              docker container rm $(docker ps --filter "status=exited")
              docker rmi $(docker images -q -f dangling=true)
