name: Deploy

on:
  push:
    tags:
      - v*
jobs:
  build_and_push_image:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::$(echo $GITHUB_REF | cut -d / -f 3)
      - name: Echo
        run: echo ${{ steps.get_version.outputs.VERSION }}
        
      - name: Build the Docker image
        run: docker build . --file Dockerfile -t auliahanifan/hello-world:${{ steps.get_version.outputs.VERSION }}
      - name: docker login
        env:
          DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        run: |
          docker login --username=$DOCKER_USERNAME --password=$DOCKER_PASSWORD

      - name: Docker Push
        run: docker push auliahanifan/hello-world:${{ steps.get_version.outputs.VERSION }}
  deploy_to_prod:
    needs: build_and_push_image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v0.1.7
        env:
          DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
          DEPLOY_CONFIG_FOLDER: ${{secrets.DEPLOY_CONFIG_FOLDER}}
          GITHUB_TAG: ${{ steps.get_version.outputs.VERSION }}
        with:
          host: ${{ secrets.SSH_SERVER }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          envs: DOCKER_USERNAME,DOCKER_PASSWORD,DEPLOY_CONFIG_FOLDER,GITHUB_TAG
          script: |
            cd $DEPLOY_CONFIG_FOLDER
            git pull origin main
            docker login --username=$DOCKER_USERNAME --password=$DOCKER_PASSWORD 
            printenv
            HELLO_TAG=$GITHUB_TAG docker stack deploy -c hello-world.docker-compose.yml hello
